export const DEFAULT_ATTRIBUTION_VERBS = ["acknowledged", "added", "admitted", "advised", "affirmed", "agreed", "announced", "answered", "argued", "asked", "barked", "began", "bellowed", "blurted", "boasted", "bragged", "called", "chirped", "commanded", "commented", "complained", "conceded", "concluded", "confessed", "confirmed", "continued", "countered", "cried", "croaked", "crowed", "declared", "decreed", "demanded", "denied", "drawled", "echoed", "emphasized", "enquired", "enthused", "estimated", "exclaimed", "explained", "gasped", "insisted", "instructed", "interjected", "interrupted", "joked", "lamented", "lied", "maintained", "moaned", "mumbled", "murmured", "mused", "muttered", "nagged", "nodded", "noted", "objected", "offered", "ordered", "perked up", "pleaded", "prayed", "predicted", "proclaimed", "promised", "proposed", "protested", "queried", "questioned", "quipped", "rambled", "reasoned", "reassured", "recited", "rejoined", "remarked", "repeated", "replied", "responded", "retorted", "roared", "said", "scolded", "scoffed", "screamed", "shouted", "sighed", "snapped", "snarled", "spoke", "stammered", "stated", "stuttered", "suggested", "surmised", "tapped", "threatened", "turned", "urged", "vowed", "wailed", "warned", "whimpered", "whispered", "wondered", "yelled"];

export const DEFAULT_ACTION_VERBS = ["adjust", "adjusted", "appear", "appeared", "approach", "approached", "arrive", "arrived", "blink", "blinked", "bow", "bowed", "charge", "charged", "chase", "chased", "climb", "climbed", "collapse", "collapsed", "crawl", "crawled", "crept", "crouch", "crouched", "dance", "danced", "dart", "darted", "dash", "dashed", "depart", "departed", "dive", "dived", "dodge", "dodged", "drag", "dragged", "drift", "drifted", "drop", "dropped", "emerge", "emerged", "enter", "entered", "exit", "exited", "fall", "fell", "flee", "fled", "flinch", "flinched", "float", "floated", "fly", "flew", "follow", "followed", "freeze", "froze", "frown", "frowned", "gesture", "gestured", "giggle", "giggled", "glance", "glanced", "grab", "grabbed", "grasp", "grasped", "grin", "grinned", "groan", "groaned", "growl", "growled", "grumble", "grumbled", "grunt", "grunted", "hold", "held", "hit", "hop", "hopped", "hurry", "hurried", "jerk", "jerked", "jog", "jogged", "jump", "jumped", "kneel", "knelt", "laugh", "laughed", "lean", "leaned", "leap", "leapt", "left", "limp", "limped", "look", "looked", "lower", "lowered", "lunge", "lunged", "march", "marched", "motion", "motioned", "move", "moved", "nod", "nodded", "observe", "observed", "pace", "paced", "pause", "paused", "point", "pointed", "pop", "popped", "position", "positioned", "pounce", "pounced", "push", "pushed", "race", "raced", "raise", "raised", "reach", "reached", "retreat", "retreated", "rise", "rose", "run", "ran", "rush", "rushed", "sit", "sat", "scramble", "scrambled", "set", "shift", "shifted", "shake", "shook", "shrug", "shrugged", "shudder", "shuddered", "sigh", "sighed", "sip", "sipped", "slip", "slipped", "slump", "slumped", "smile", "smiled", "snort", "snorted", "spin", "spun", "sprint", "sprinted", "stagger", "staggered", "stare", "stared", "step", "stepped", "stand", "stood", "straighten", "straightened", "stumble", "stumbled", "swagger", "swaggered", "swallow", "swallowed", "swap", "swapped", "swing", "swung", "tap", "tapped", "throw", "threw", "tilt", "tilted", "tiptoe", "tiptoed", "take", "took", "toss", "tossed", "trudge", "trudged", "turn", "turned", "twist", "twisted", "vanish", "vanished", "wake", "woke", "walk", "walked", "wander", "wandered", "watch", "watched", "wave", "waved", "wince", "winced", "withdraw", "withdrew"];

export const EXTENDED_ATTRIBUTION_VERBS = [
    'acknowledged', 'ad-libbed', 'addressed', 'affirmed', 'announced',
    'answered', 'argued', 'articulated', 'asserted', 'assented', 'assured',
    'averred', 'avowed', 'babbled', 'bantered', 'barked', 'beamed', 'bellowed',
    'beseeched', 'bleated', 'blustered', 'boasted', 'boomed', 'bragged', 'brayed',
    'breathed', 'cackled', 'cajoled', 'cautioned', 'chanted', 'chided',
    'chimed', 'chirped', 'chuckled', 'clarified', 'clucked', 'coached', 'cooed',
    'conceded', 'confessed', 'consoled', 'countered', 'croaked', 'crooned',
    'cursed', 'decreed', 'declaimed', 'denied', 'demanded', 'detailed',
    'dictated', 'drawled', 'droned', 'elaborated', 'emphasized', 'enjoined',
    'enthused', 'exclaimed', 'expounded', 'explained', 'fumed', 'gasped',
    'giggled', 'grinned', 'groaned', 'growled', 'grumbled', 'grunted',
    'hissed', 'hollered', 'howled', 'implored', 'inquired', 'insinuated',
    'insisted', 'interjected', 'intoned', 'jabbed', 'jested', 'joked',
    'lamented', 'lectured', 'marveled', 'mentioned', 'mewled', 'mimicked',
    'mumbled', 'murmured', 'mused', 'muttered', 'nagged', 'narrated', 'noted', 'observed',
    'opined', 'panted', 'persisted', 'persuaded', 'petitioned', 'phoned',
    'piped', 'pleaded', 'prattled', 'preached', 'proclaimed', 'promised',
    'pronounced', 'proposed', 'protested', 'purred', 'quavered', 'questioned',
    'quipped', 'quoted', 'rasped', 'reasoned', 'reassured', 'recited',
    'remarked', 'repeated', 'replied', 'reported', 'requested', 'responded',
    'retorted', 'roared', 'sang', 'sassed', 'scoffed', 'seethed', 'shouted',
    'shrieked', 'sighed', 'smirked', 'snapped', 'snarled', 'sniffled',
    'sobbed', 'soothed', 'spat', 'speculated', 'spluttered', 'sputtered',
    'stammered', 'stated', 'suggested', 'taunted', 'teased', 'threatened',
    'trilled', 'twittered', 'urged', 'voiced', 'wailed', 'warned',
    'whimpered', 'whined', 'whispered', 'whooped', 'yammered', 'yapped',
    'yelled', 'yowled',
];

export const EXTENDED_ACTION_VERBS = [
    'advanced', 'ambled', 'arced', 'brandished', 'braved', 'breathed',
    'bristled', 'buckled', 'careened', 'carved', 'cast', 'charged', 'churned',
    'clambered', 'clattered', 'clenched', 'cloaked', 'clutched', 'coiled',
    'collided', 'commanded', 'conjured', 'cowered', 'cradled', 'crashed',
    'crawled', 'cringed', 'crumpled', 'darted', 'dashed', 'dazzled', 'debated',
    'descended', 'detonated', 'dove', 'dragged', 'drank', 'drifted', 'dropped',
    'edged', 'embraced', 'encircled', 'engulfed', 'entwined', 'erupted',
    'evaded', 'examined', 'exhaled', 'exploded', 'extended', 'faltered',
    'fidgeted', 'flashed', 'fled', 'flinched', 'flourished', 'fluttered',
    'focused', 'forged', 'fumbled', 'galloped', 'gasped', 'gathered',
    'glided', 'glimmered', 'glowered', 'gnashed', 'grappled', 'grimaced',
    'gripped', 'groaned', 'halted', 'hastened', 'hauled', 'hesitated',
    'huddled', 'hurtled', 'ignited', 'illuminated', 'inched', 'infused',
    'intercepted', 'jolted', 'jostled', 'kindled', 'lashed', 'launched',
    'leaned', 'lingered', 'loomed', 'lunged', 'manipulated', 'marched',
    'manifested', 'maneuvered', 'melted', 'mustered', 'navigated', 'nudged',
    'observed', 'orbited', 'padded', 'panned', 'parried', 'perched', 'pierced',
    'pivoted', 'planted', 'plummeted', 'pounced', 'poured', 'pried', 'pulled',
    'quivered', 'raced', 'radiated', 'rallied', 'rattled', 'reacted',
    'recoiled', 'recovered', 'reigned', 'relented', 'remained', 'rendered',
    'retreated', 'revolved', 'rippled', 'rolled', 'rose', 'sauntered',
    'scampered', 'scanned', 'scattered', 'scowled', 'scrabbled', 'scraped',
    'seized', 'shattered', 'shimmered', 'shivered', 'shrunk', 'sidestepped',
    'skidded', 'slammed', 'slashed', 'slid', 'slithered', 'slumped', 'smirked',
    'smoldered', 'snapped', 'snatched', 'soared', 'softened', 'spiraled',
    'splashed', 'sprinted', 'sputtered', 'squared', 'stalked', 'steadied',
    'stormed', 'strafed', 'strayed', 'struggled', 'stumbled', 'sundered',
    'surged', 'swayed', 'swiveled', 'swung', 'swirled', 'tackled', 'taunted',
    'teetered', 'thrashed', 'threw', 'thrust', 'thudded', 'thundered',
    'tilted', 'tracked', 'trailed', 'trampled', 'trembled', 'trudged',
    'twirled', 'twisted', 'unfurled', 'vanished', 'vaulted', 'veered',
    'wavered', 'whipped', 'whirled', 'widened', 'wielded', 'winced',
    'wove', 'writhed', 'yanked', 'yearned', 'zigzagged',
];
